#pragma once
#include <iostream>
#include <cmath>
#include <stdexcept>
#include <string>
#include <sstream>
#include <vector>
#include <fstream>
#include <set>
#include <algorithm>
#include <list>
#include <map>
#include <unordered_map>
#include <functional>
#include <thread>
#include <random>
#include <chrono>
#include <iterator>
#include <stdlib.h>
#include <assert.h>